CREATE TABLE teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_teams_tenant_name UNIQUE (tenant_id, name),
    CONSTRAINT uk_teams_id_tenant UNIQUE (id, tenant_id),
    CONSTRAINT fk_teams_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON DELETE RESTRICT
);

CREATE TABLE queues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_queues_tenant_name UNIQUE (tenant_id, name),
    CONSTRAINT fk_queues_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_queues_team_tenant
        FOREIGN KEY (team_id, tenant_id) REFERENCES teams (id, tenant_id)
        ON DELETE RESTRICT
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_categories_tenant_name UNIQUE (tenant_id, name),
    CONSTRAINT fk_categories_tenant
        FOREIGN KEY (tenant_id) REFERENCES tenants (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_teams_tenant_active
    ON teams (tenant_id, active);

CREATE INDEX idx_queues_tenant_active
    ON queues (tenant_id, active);

CREATE INDEX idx_queues_tenant_team
    ON queues (tenant_id, team_id);

CREATE INDEX idx_categories_tenant_active
    ON categories (tenant_id, active);
