CREATE TABLE tickets (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL,
 ticket_number VARCHAR(40) NOT NULL,
 requester_id BIGINT NOT NULL,
 assignee_id BIGINT,
 title VARCHAR(240) NOT NULL,
 description TEXT NOT NULL,
 priority VARCHAR(32) NOT NULL,
 status VARCHAR(40) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT uk_tickets_tenant_number UNIQUE (tenant_id,ticket_number),
 CONSTRAINT fk_tickets_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
 CONSTRAINT fk_tickets_requester FOREIGN KEY (requester_id) REFERENCES users(id),
 CONSTRAINT fk_tickets_assignee FOREIGN KEY (assignee_id) REFERENCES users(id),
 CONSTRAINT ck_tickets_priority CHECK (priority IN ('CRITICAL','HIGH','MEDIUM','LOW')),
 CONSTRAINT ck_tickets_status CHECK (status IN ('OPEN','IN_PROGRESS','WAITING_FOR_REQUESTER','RESOLVED','CLOSED','CANCELLED'))
);
CREATE INDEX idx_tickets_tenant_status ON tickets(tenant_id,status);
CREATE INDEX idx_tickets_tenant_priority ON tickets(tenant_id,priority);
CREATE INDEX idx_tickets_tenant_assignee ON tickets(tenant_id,assignee_id);
CREATE TABLE ticket_comments (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL,
 ticket_id BIGINT NOT NULL,
 author_id BIGINT NOT NULL,
 body TEXT NOT NULL,
 visibility VARCHAR(20) NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_comments_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
 CONSTRAINT fk_comments_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,
 CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users(id),
 CONSTRAINT ck_comments_visibility CHECK (visibility IN ('REQUESTER','INTERNAL'))
);
CREATE INDEX idx_comments_ticket_created ON ticket_comments(tenant_id,ticket_id,created_at);
