CREATE TABLE tasks (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 tenant_id BIGINT NOT NULL,
 ticket_id BIGINT,
 assignee_id BIGINT,
 title VARCHAR(240) NOT NULL,
 description TEXT,
 priority VARCHAR(32) NOT NULL,
 status VARCHAR(32) NOT NULL,
 due_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_tasks_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
 CONSTRAINT fk_tasks_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id),
 CONSTRAINT fk_tasks_assignee FOREIGN KEY (assignee_id) REFERENCES users(id),
 CONSTRAINT ck_tasks_priority CHECK (priority IN ('CRITICAL','HIGH','MEDIUM','LOW')),
 CONSTRAINT ck_tasks_status CHECK (status IN ('TODO','IN_PROGRESS','BLOCKED','DONE','CANCELLED'))
);
CREATE INDEX idx_tasks_tenant_assignee_status_due ON tasks(tenant_id,assignee_id,status,due_at);
