CREATE TABLE audit_logs(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,tenant_id BIGINT NOT NULL,actor_user_id BIGINT NOT NULL,action VARCHAR(80) NOT NULL,target_type VARCHAR(80) NOT NULL,target_id BIGINT,details_json TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_audit_tenant FOREIGN KEY(tenant_id) REFERENCES tenants(id),CONSTRAINT fk_audit_actor FOREIGN KEY(actor_user_id) REFERENCES users(id));
CREATE INDEX idx_audit_tenant_created ON audit_logs(tenant_id,created_at);
CREATE INDEX idx_audit_tenant_action ON audit_logs(tenant_id,action);
