package com.servicedesk360.service;

import com.servicedesk360.dto.common.PageResponse; import com.servicedesk360.dto.task.*; import com.servicedesk360.entity.*; import com.servicedesk360.exception.*; import com.servicedesk360.repository.*; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service public class TaskService{
 private final TaskRepository tasks; private final UserRepository users; private final TicketRepository tickets; private final CurrentUserService current; private final NotificationService notifications;
 public TaskService(TaskRepository tasks,UserRepository users,TicketRepository tickets,CurrentUserService current,NotificationService notifications){this.tasks=tasks;this.users=users;this.tickets=tickets;this.current=current;this.notifications=notifications;}
 @Transactional public TaskResponse create(TaskCreateRequest r){var me=current.getRequiredUser(); if(me.role()==Role.REQUESTER)throw new UnauthorizedException("Requester cannot create employee tasks"); var assignee=r.assigneeId()==null?null:findUser(r.assigneeId(),me.tenantId()); var ticket=r.ticketId()==null?null:tickets.findByIdAndTenantId(r.ticketId(),me.tenantId()).orElseThrow(()->new ResourceNotFoundException("Ticket not found")); var saved=tasks.save(new Task(me.tenantId(),ticket,assignee,r.title().trim(),r.description(),r.priority(),r.dueAt())); if(assignee!=null)notifications.create(me.tenantId(),assignee.getId(),"TASK_ASSIGNED","New task assigned",saved.getTitle(),"TASK",saved.getId()); return TaskResponse.from(saved);}
 @Transactional(readOnly=true) public PageResponse<TaskResponse> list(Pageable p){var me=current.getRequiredUser(); Page<Task> page=switch(me.role()){case REQUESTER->Page.empty(p);case AGENT->tasks.findAllByTenantIdAndAssigneeId(me.tenantId(),me.user().getId(),p);case MANAGER,TENANT_ADMIN,PLATFORM_ADMIN->tasks.findAllByTenantId(me.tenantId(),p);}; return PageResponse.from(page.map(TaskResponse::from));}
 @Transactional public TaskResponse update(Long id,TaskUpdateRequest r){var me=current.getRequiredUser(); Task t=find(id,me.tenantId()); if(me.role()==Role.REQUESTER)throw new UnauthorizedException("Requesters cannot update employee tasks"); if(me.role()==Role.AGENT&&(t.getAssignee()==null||!me.user().getId().equals(t.getAssignee().getId())))throw new UnauthorizedException("Agent can update only assigned tasks"); if(r.title()!=null&&!r.title().isBlank())t.setTitle(r.title().trim()); if(r.description()!=null)t.setDescription(r.description()); if(r.priority()!=null)t.setPriority(r.priority()); if(r.dueAt()!=null)t.setDueAt(r.dueAt()); if(r.assigneeId()!=null){if(me.role()==Role.AGENT)throw new UnauthorizedException("Agents cannot reassign tasks");t.setAssignee(findUser(r.assigneeId(),me.tenantId()));} return TaskResponse.from(t);}
 @Transactional public TaskResponse status(Long id,TaskStatusRequest r){var me=current.getRequiredUser(); Task t=find(id,me.tenantId()); if(me.role()==Role.REQUESTER)throw new UnauthorizedException("Requesters cannot update employee tasks"); if(me.role()==Role.AGENT&&(t.getAssignee()==null||!me.user().getId().equals(t.getAssignee().getId())))throw new UnauthorizedException("Agent can update only assigned tasks"); if(!allowed(t.getStatus(),r.status()))throw new BusinessException("INVALID_TASK_STATUS_TRANSITION","Task cannot move from "+t.getStatus()+" to "+r.status()); t.setStatus(r.status()); return TaskResponse.from(t);}
 private User findUser(Long id,Long tenant){return users.findByIdAndTenantId(id,tenant).orElseThrow(()->new ResourceNotFoundException("Assignee not found"));} private Task find(Long id,Long tenant){return tasks.findByIdAndTenantId(id,tenant).orElseThrow(()->new ResourceNotFoundException("Task not found"));}
 private boolean allowed(TaskStatus f,TaskStatus t){return switch(f){case TODO->t==TaskStatus.IN_PROGRESS||t==TaskStatus.BLOCKED||t==TaskStatus.CANCELLED;case BLOCKED->t==TaskStatus.IN_PROGRESS||t==TaskStatus.CANCELLED;case IN_PROGRESS->t==TaskStatus.DONE||t==TaskStatus.BLOCKED||t==TaskStatus.CANCELLED;case DONE,CANCELLED->false;};}
}
