import { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { addComment, changeTicketPriority, changeTicketStatus, getComments, getTicket } from '../api/ticketApi';
import { useAuth } from '../context/AuthContext';

const transitions = { OPEN: ['IN_PROGRESS', 'CANCELLED'], IN_PROGRESS: ['WAITING_FOR_REQUESTER', 'RESOLVED'], WAITING_FOR_REQUESTER: ['IN_PROGRESS'], RESOLVED: ['CLOSED', 'IN_PROGRESS'] };
export default function TicketDetailsPage() {
  const { id } = useParams(); const navigate = useNavigate(); const { token, user } = useAuth();
  const [ticket, setTicket] = useState(null); const [comments, setComments] = useState([]); const [comment, setComment] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const [t, c] = await Promise.all([getTicket(token, id), getComments(token, id)]); setTicket(t); setComments(c); }, [token, id]);
  useEffect(() => { load().catch(e => setError(e.message)); }, [load]);
  const run = async (action, message) => { setError(''); setSuccess(''); setBusy(true); try { await action(); await load(); setSuccess(message); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const submitComment = event => { event.preventDefault(); if (!comment.trim()) return; run(async () => { await addComment(token, id, comment, user?.role === 'REQUESTER' ? 'REQUESTER' : 'INTERNAL'); setComment(''); }, 'Comment added.'); };
  if (error && !ticket) return <section><div className="error">{error}</div><Link className="back-link" to="/app/tickets">← Back to tickets</Link></section>;
  if (!ticket) return <section><p>Loading ticket...</p></section>;
  const allowed = transitions[ticket.status] || [];
  return <section className="detail-page"><div className="detail-top"><div><Link className="back-link" to="/app/tickets">← All tickets</Link><span className="eyebrow">{ticket.ticketNumber}</span><h1>{ticket.title}</h1></div><span className={`status-tag status-${ticket.status.toLowerCase()}`}>{ticket.status}</span></div>{error && <div className="error">{error}</div>}{success && <div className="success">{success}</div>}<div className="detail-grid"><article className="detail-card"><div className="detail-meta"><span className={`priority-tag priority-${ticket.priority.toLowerCase()}`}>{ticket.priority}</span><span>Requester #{ticket.requesterId}</span><span>Assignee {ticket.assigneeId ? `#${ticket.assigneeId}` : 'Unassigned'}</span></div><p className="ticket-description">{ticket.description}</p><div className="sla-box"><div><small>First response due</small><b>{ticket.firstResponseDueAt ? new Date(ticket.firstResponseDueAt).toLocaleString() : 'Not configured'}</b></div><div><small>Resolution due</small><b>{ticket.resolutionDueAt ? new Date(ticket.resolutionDueAt).toLocaleString() : 'Not configured'}</b></div></div><div className="detail-actions"><label>Status<select value={ticket.status} onChange={e => run(() => changeTicketStatus(token, id, e.target.value), `Ticket moved to ${e.target.value}.`)} disabled={busy || !allowed.length}><option>{ticket.status}</option>{allowed.map(status => <option key={status}>{status}</option>)}</select></label><label>Priority<select value={ticket.priority} onChange={e => run(() => changeTicketPriority(token, id, e.target.value), 'Priority updated.')} disabled={busy || !['MANAGER','TENANT_ADMIN'].includes(user?.role)}>{['LOW','MEDIUM','HIGH','CRITICAL'].map(priority => <option key={priority}>{priority}</option>)}</select></label></div></article><aside className="detail-card comments-card"><h2>Conversation</h2><div className="comment-list">{comments.length ? comments.map(item => <div className="comment" key={item.id}><div><b>User #{item.authorId}</b><small>{item.visibility} · {new Date(item.createdAt).toLocaleString()}</small></div><p>{item.body}</p></div>) : <p className="muted">No comments yet.</p>}</div><form className="comment-form" onSubmit={submitComment}><textarea placeholder="Add context or an update..." value={comment} onChange={e => setComment(e.target.value)} /><button className="button button-primary" disabled={busy || !comment.trim()}>Add comment <span>↗</span></button></form></aside></div></section>;
}
